#include<stdio.h>
#include<string.h>
int main ()
{
    int i,j=0,k,x,l,n,ar[2][2];
    char s[100];
    scanf("%d",&i);
    while(i>0)
    {
        ar[0][0]=1;
        ar[0][1]=0;
        ar[1][0]=0;
        ar[1][1]=0;
        scanf("%s",s);
        k=strlen(s);
        for(j=0; j<k; j++)
        {
            if(s[j]=='A')
            {
                x=ar[1][0];
                ar[1][0]=ar[0][1];
                ar[0][1]=x;
            }
            if(s[j]=='B')
            {
                x=ar[0][0];
                ar[0][0]=ar[1][1];
                ar[1][1]=x;
            }
            if(s[j]=='C')
            {
                x=ar[0][0];
                ar[0][0]=ar[1][0];
                ar[1][0]=x;
                x=ar[0][1];
                ar[0][1]=ar[1][1];
                ar[1][1]=x;
            }
            if(s[j]=='D')
            {
                x=ar[0][0];
                ar[0][0]=ar[0][1];
                ar[0][1]=x;
                x=ar[1][0];
                ar[1][0]=ar[1][1];
                x=ar[1][1];
            }
            if(s[j]=='E')
            {
                x=ar[0][0];
                ar[0][0]=ar[1][1];
                ar[1][1]=x;
                x=ar[1][0];
                ar[1][0]=ar[0][1];
                x=ar[0][1];
            }
        }
        if(ar[0][0]==1)
        {
            printf("1");
        }
        if(ar[0][1]==1)
        {
            printf("2");
        }
        if(ar[1][0]==1)
        {
            printf("3");
        }
        if(ar[1][1]==1)
        {
            printf("4");
        }
        i--;
    }

    return 0;
}
